@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class BostonUniversity {
  - instance: BostonUniversity
  - departments: List<Department>
  + findDepartment(String): Optional<Department>
   instance: BostonUniversity
   departments: List<Department>
}
class ComputerScienceDepartment {
  - instance: ComputerScienceDepartment
   name: String
   instance: Department
   builder: DepartmentBuilder<T>
}
class ComputerScienceDepartmentBuilder {
  + addPrograms(): void
  + addFaculty(): void
  + addCoursesAndConcentrations(): void
  + addClassOfferings(): void
  + build(): ComputerScienceDepartment
}
class Department {
  - registrar: Registrar
  - courses: Set<Course>
  - concentrations: Set<Concentration>
  - students: Set<Student>
  - programs: Set<Program>
  - chairPerson: Faculty
  - faculty: Set<Faculty>
  + addThesis(Student, Thesis, Semester, Faculty): void
  + getUnderGraduateAdvisor(SchoolYear): Optional<Faculty>
  + findCourse(String): Optional<Course>
  + addGraduateAdvisor(SchoolYear, Faculty): void
  + findFaculty(String): Optional<Faculty>
  + addFaculty(Faculty): void
  + addUnderGraduateAdvisor(SchoolYear, Faculty): void
  + sendMessageToChairPerson(Person, String, String): void
  + assignGrade(Student, String, CourseGrade): void
  + sendMessageToFaculty(Person, Faculty, String, String): void
  + getGraduateAdvisor(SchoolYear): Optional<Faculty>
  + enrollProgram(Student, String): void
  + createElectiveCourse(String, String, String): Elective
  + enrollProgram(Student, Program): void
  + findProgram(String): Optional<Program>
  + findStudent(String): Optional<Student>
  + createCoreCourse(String, String, String): Core
  + addProgram(Program): void
  + addConcentration(Concentration): void
   name: String
   builder: DepartmentBuilder<T>
   faculty: Collection<Faculty>
   courses: Set<Course>
   programs: Collection<Program>
   defaultGpaComputeStrategy: GpaComputeStrategy
   students: Collection<Student>
   chairPerson: Faculty
   classOfferings: Collection<ClassOffering>
   registrar: Registrar
   concentrations: Collection<Concentration>
}
interface DepartmentBuilder<T> << interface >> {
  + addClassOfferings(): void
  + addCoursesAndConcentrations(): void
  + addFaculty(): void
  + addPrograms(): void
  + build(): T
}

BostonUniversity                 "1" *-[#595959,plain]-> "instance\n1" BostonUniversity                 
BostonUniversity                  -[#595959,dashed]->  BostonUniversity                 : "«create»"
BostonUniversity                 "1" *-[#595959,plain]-> "departments\n*" Department                       
ComputerScienceDepartment        "1" *-[#595959,plain]-> "instance\n1" ComputerScienceDepartment        
ComputerScienceDepartment         -[#595959,dashed]->  ComputerScienceDepartment        : "«create»"
ComputerScienceDepartment         -[#595959,dashed]->  ComputerScienceDepartmentBuilder : "«create»"
ComputerScienceDepartment         -[#000082,plain]-^  Department                       
ComputerScienceDepartmentBuilder  +-[#820000,plain]-  ComputerScienceDepartment        
ComputerScienceDepartmentBuilder  -[#595959,dashed]->  ComputerScienceDepartment        : "«create»"
ComputerScienceDepartmentBuilder "1" *-[#595959,plain]-> "instance\n1" ComputerScienceDepartment        
ComputerScienceDepartmentBuilder  -[#008200,dashed]-^  DepartmentBuilder                
DepartmentBuilder                 +-[#820000,plain]-  Department                       
@enduml
