@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class BusinessCustomer
class Customer {
  + addAccount(Account): void
  + toString(): String
  + hashCode(): int
  + equals(Object): boolean
   name: String
   address: Optional<Address>
   registrationDate: LocalDate
   accounts: List<Account>
   phoneNumber: Optional<String>
}
enum CustomerType << enumeration >> {
  + values(): CustomerType[]
  + valueOf(String): CustomerType
}
class PreferredCustomer
class SimpleCustomerFactory {
  + createCustomer(CustomerType): Customer
   instance: SimpleCustomerFactory
}
class StandardCustomer

BusinessCustomer       -[#000082,plain]-^  Customer              
PreferredCustomer      -[#000082,plain]-^  Customer              
SimpleCustomerFactory  -[#595959,dashed]->  BusinessCustomer      : "«create»"
SimpleCustomerFactory  -[#595959,dashed]->  PreferredCustomer     : "«create»"
SimpleCustomerFactory "1" *-[#595959,plain]-> "instance\n1" SimpleCustomerFactory 
SimpleCustomerFactory  -[#595959,dashed]->  SimpleCustomerFactory : "«create»"
SimpleCustomerFactory  -[#595959,dashed]->  StandardCustomer      : "«create»"
StandardCustomer       -[#000082,plain]-^  Customer              
@enduml
